apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: go-app-03181-repository
spec:
  url: https://github.com/stephanie-cy/go-app-03181
  # secret:
  #     name: "gitops-auth-secret"
  #     # Set this if you have a different key in your secret
  #     key: "password"
  # webhook_secret:
  #     name: "rhtap-pipeline-secret"
  #     # Set this if you have a different key in your secret
  #     key: "webhook-github-secret"
  params:
    - name: secret
      secretRef:
        name: "gitops-auth-secret"
        key: "password"
    - name: webhook_secret
      secretRef:
        name: "rhtap-pipeline-secret"
        key: "webhook-github-secret"
